#!/bin/bash
# root: y

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

############

error_msg() {
	echo -e "$red""$1""$end"
	exit 1
}

status_msg() {
	echo -e "$blue""\n[~] $1""$end"
}

############

need_root() {
	if [ "$UID" != "0" ]; then
		error_msg "Root needed using su. Run as root this script!"
	fi
}

need_root

############

status_msg "Backup old file if exists"

if [ -e /etc/apt/apt.conf ]; then
	cp -f /etc/apt/apt.conf /etc/apt/apt.conf.backup
	rm /etc/apt/apt.conf
fi

touch /etc/apt/apt.conf

echo "APT::Install-Recommends \"false\";
APT::Install-Suggests \"false\";
APT::GET::Install-Recommends \"false\";
APT::GET::Install-Suggests \"false\";" > /etc/apt/apt.conf

status_msg "Reload repository configuration"

############

apt update

############

status_msg "Done"
exit 0
