#!/bin/bash
# root: n

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

############

error_msg() {
	echo -e "$red""$1""$end"
	exit 1
}

status_msg() {
	echo -e "$blue""[~] $1""$end"
}

############

install_dep() {
	checkdep=`which exiftool`
	if [ "$checkdep" == "" ]; then
		error_msg "Install manually exiftool"
	fi
}

install_dep

install_dep() {
	checkdep=`which mat2`
	if [ "$checkdep" == "" ]; then
		error_msg "Install manually mat2"
	fi
}

install_dep

############

usage() {
	echo -e "$purple
Usage: $0 [-f|-d 'document'|'docs/'] $end
Details:
-$cyan -f|-d 'document'|'docs/'$end: you must choose a simple file or a folder
$end"
	exit 0
}

if [[ ${#} -eq '' ]] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	usage
fi

############

while getopts f:d: flag
do
	case "${flag}" in
		f) thefile=${OPTARG};;
		d) thefolder=${OPTARG};;
	esac
done

############

status_msg "Proceed the deletion of metadatas"

if [ -e "$thefile" ]; then
	mat2 --inplace "$thefile"
fi

if [ -d "$thefolder" ]; then
	find "$thefolder" -type f -exec mat2 --inplace {} \;
fi

############

status_msg "Done"
exit 0
