#!/bin/bash
# root: n

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

############

error_msg() {
	echo -e "$red""$1""$end"
	exit 1
}

############

usage() {
	echo -e "$purple
Usage: $0 [-i 'input.jpg'] (-d)$end
Details:
-$cyan -i 'input.jpg'$end: the image to convert. If png, convert to jpeg. If jpeg, convert to png.
-$cyan -d$end: delete the original file
$end"
	exit 0
}

if [[ ${#} -eq '' ]] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	usage
fi

############

isdelete=false

while getopts i:d flag
do
	case "${flag}" in
		i) input=${OPTARG};;
		d) isdelete=true;;
	esac
done

if [ ! -e "$input" ] || [ "$input" == "" ]; then
	error_msg "Input file not exist or null!"
fi

############

inext=`echo "$input" | cut -d'.' -f2`
directory=`pwd "$input"`

cd "$directory"

if [ "$inext" == "png" ]; then
	mogrify -format jpeg "$input"
elif [ "$inext" == "jpeg" ] || [ "$inext" == "jpg" ]; then
	mogrify -format png "$input"
else
	error_msg "Extension not supported!"
fi

if ($isdelete); then
	rm "$input"
fi

############

exit 0
