#!/bin/bash
# root: n

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

############

error_msg() {
	echo -e "$red""$1""$end"
	exit 1
}

############

usage() {
	echo -e "$purple
Usage: $0 [-s '480x480'] [-i 'input.jpg'] (-o 'output.jpg') $end
Details:
-$cyan -s '480x480'$end: size to resize
-$cyan -i 'input.jpg'$end: the image to resize
-$cyan -o 'output.jpg'$end: optionally an output file if you do not want to overwrite the original file
$end"
	exit 0
}

if [[ ${#} -eq '' ]] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	usage
fi

############

isoutput=false

while getopts s:i:o: flag
do
	case "${flag}" in
		s) size=${OPTARG};;
		i) input=${OPTARG};;
		o) isoutput=true; output=${OPTARG};;
	esac
done

if [ ! -e "$input" ] || [ "$input" == "" ]; then
	error_msg "Input file not exist or null!"
fi

if [ -e "$output" ]; then
	error_msg "Output file already exists!"
fi

############

if ($isoutput); then
	convert "$input" -resize "$size"\! "$output"
else
	convert "$input" -resize "$size"\! "$input"
fi

############

exit 0
