#!/bin/bash
# root: y

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

############

error_msg() {
	echo -e "$red""$1""$end"
	exit 1
}

warning_msg() {
	echo -e "$orange""$1""$end"
}

success_msg() {
	echo -e "$green""$1""$end"
}

status_msg() {
	echo -e "$blue""\n[~] $1""$end"
}

############

dep=`which nmcli`
if [ "$dep" == "" ]; then
	error_msg "This script is made to connect manually saved networks on network-manager!"
fi

checknetwork=`nmcli radio wifi | grep 'enabled'`
if [ "$checknetwork" == "" ]; then
	nmcli radio wifi on
	
	checknetwork=`nmcli radio wifi | grep 'enabled'`
	if [ "$checknetwork" == "" ]; then
		error_msg "Try to enable wifi card manually. This command can help you: 'nmcli radio wifi on'"
	fi
fi

############

usage() {
	echo -e "$purple
Usage: $0 [-n 'WifiName'] [-p 'MyWifiSuperPassword']$end
Details:
-$cyan -n 'WifiName'$end: the SSID (name) of the Access point you want to connect to. If you don't know it, try the command: 'nmcli dev wifi list'
-$cyan -p 'MyWifiSuperPassword'$end: password of the Access point
$end"
	exit 0
}

if [[ ${#} -eq '' ]] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	usage
fi

############

while getopts n:p: flag
do
	case "${flag}" in
		n) ssid=${OPTARG};;
		p) password=${OPTARG};;
	esac
done

if [ "$ssid" == "" ] || [ "$password" == "" ]; then
	usage
fi

############

status_msg "Proceed the deletion of metadatas"

nmcli dev wifi connect "$ssid" password "$password"

############

status_msg "Check the connection"

ipaddr=`curl "ifconfig.me"`
if [ "$ipaddr" == "" ]; then
	warning_msg "Connection: FAILED"
else
	success_msg "Connection: OK"
fi

############

status_msg "Done"
exit 0
