#!/bin/bash
# root: y

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

rndstr=`tr -dc "A-Z0-9" < /dev/urandom | head -c8`

############

error_msg() {
	echo -e "$red""$1""$end"
	exit 1
}

info_msg() {
	echo -e "$purple""$1""$end"
}

status_msg() {
	echo -e "$blue""\n[~] $1""$end"
}

mini_msg() {
	echo -e "$cyan""\t-> $1""$end"
}

############

dep=`which nmcli`
if [ "$dep" == "" ]; then
	error_msg "This script is made to connect manually saved networks on network-manager!"
fi

############

status_msg "List all saved connections"

nmcli -t -m tabular c show | sed '/UUID/d' > /tmp/connections_$rndstr.txt

############

status_msg "Parse all connections"

i=1
profile=()
uuid=()
types=()
device=()

while IFS='' read -r line || [[ -n "$line" ]]; do
	mini_msg "Connection: $i"
	
	profiletmp=`echo "$line" | cut -d':' -f1`
	uuidtmp=`echo "$line" | cut -d':' -f2`
	typestmp=`echo "$line" | cut -d':' -f3`
	devicetmp=`echo "$line" | cut -d':' -f4`
	
	profile+=("$profiletmp")
	uuid+=("$uuidtmp")
	types+=("$typestmp")
	device+=("$devicetmp")
	
	let i=i+1
done < /tmp/connections_$rndstr.txt

############

status_msg "List all connections"

countuuid=`echo ${#uuid[@]}`
choice=""

z=1
n=0

while [ "$z" -le "$countuuid" ]; do
	n=`echo "$z - 1" | bc`
	
	if [ "$choice" == "" ]; then
		choice="\n$z. ${profile[$n]} (Type: ${types[$n]} | Device: ${device[$n]})\n"
	else
		choice="$choice$z. ${profile[$n]} (Type: ${types[$n]} | Device: ${device[$n]})\n"
	fi
	
	let z=z+1
done

choice="$choice\nPlease choose the connection you want to use using the integer: "

echo -e -n "$choice"
read answer

if [[ $answer =~ ^[0-9]+$ ]]; then
	theindex=`echo "$answer - 1" | bc`
	
	check="${profile[$theindex]}"
	if [ "$check" == "" ]; then
		error_msg "Your choice is incorrect!"
	fi
	
	info_msg "\nProfile chosen:\n\nName: ${profile[$theindex]}\nUUID: ${uuid[$theindex]}\nType: ${types[$theindex]}\nDevice: ${device[$theindex]}"
else
	error_msg "The answer is not an integer!"
fi

############

status_msg "Connect the profile"

nmcli c up ${uuid[$theindex]}

############

status_msg "Done"
exit 0
