#!/bin/bash
# root: n

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

############

status_msg() {
	echo -e "$blue""\n[~] $1""$end"
}

############

status_msg "Delete Python3 PIP Modules"

pip3 freeze --user | xargs pip3 uninstall -y

############

status_msg "Done"
exit 0
