#!/bin/bash
# root: y

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

rnd=`tr -dc "a-z0-9" < /dev/urandom | head -c16`

############

need_root() {
	if [ "$UID" != "0" ]; then
		echo -e "$red""Root is needed!""$end"
		exit 1
	fi
}

need_root

############

patch_wayland() {
	sed -i 's;#WaylandEnable=false;WaylandEnable=false;g' /etc/gdm3/daemon.conf
}

############

patch_wayland

echo -e "$blue""Patched""$end"
exit 0
