#!/bin/bash
# root: y

createbackup=false

############

grey="\\e[1;90m"
red="\\e[1;91m"
green="\\e[1;92m"
orange="\\e[1;93m"
blue="\\e[1;94m"
purple="\\e[1;95m"
cyan="\\e[1;96m"
white="\\e[1;97m"
end="\\e[0;0m"

rnd=`tr -dc "a-z0-9" < /dev/urandom | head -c16`

############

need_root() {
	if [ "$UID" != "0" ]; then
		echo -e "$red""Root is needed!""$end"
		exit 1
	fi
}

need_root

############

get_version_extended() {
	echo `ls /usr/lib/x86_64-linux-gnu/libcurl.so.* | sort -u | tail -1 | rev | cut -d'/' -f1 | rev`
}

extended=`get_version_extended`

get_version_classic() {
	echo `ls /usr/lib/x86_64-linux-gnu/libcurl.so.* | sort -u | head -1 | rev | cut -d'/' -f1 | rev`
}

classic=`get_version_classic`

create_backup() {
	if ($createbackup); then
		cp /usr/lib/x86_64-linux-gnu/$extended /usr/lib/x86_64-linux-gnu/$extended
		cp /usr/lib/x86_64-linux-gnu/$classic /usr/lib/x86_64-linux-gnu/$classic
	fi
}

create_sym_link() {
	ln -s /usr/lib/x86_64-linux-gnu/$classic /usr/local/lib/$classic
	ln -s /usr/lib/x86_64-linux-gnu/$extended /usr/local/lib/$extended
}

############

create_backup
create_sym_link

echo -e "$blue""Patched""$end"

exit 0
